### PR TITLE
update conversation.md and system-config.md for dak

### PR DESCRIPTION
**Pull request by windsonsea**
更新 2 篇文档的图文

### CODE REVIEW

**Comment by samzong** [comment]
AI 对话好像被移除了，  @Zhuzhenghao pls confirm it.

**Comment by windsonsea** [comment]
ok, this will be closed

**Comment by windsonsea** [comment]
ok, 按最新 UI 更新了截图和文字

**Review by samzong — APPROVED** [review]
/lgtm

**Pull request merged**
